name: Publish jar to GitHub
on:
    release:
        types: [ created ]
jobs:
    publish-github:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout action
                uses: actions/checkout@v3
            -   name: Set up Java
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
            -   name: Build the jar file
                run: ./gradlew jar buildJavadocZip
                working-directory: code
            -   name: Publish jar to GitHub
                uses: AButler/upload-release-assets@v2.0
                with:
                    files: 'code/build/libs/*'
                    repo-token: ${{ secrets.GITHUB_TOKEN }}
