# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [ pull_request ]

jobs:
    build-and-test:
        name: "Build and Test"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
            -   name: Build with Gradle
                run: ./gradlew build
                working-directory: code
            -   name: Upload Unit Test Results
                if: always()
                uses: actions/upload-artifact@v2
                with:
                    name: Unit Test Results
                    path: test-results/**/*.xml

    publish-test-results:
        name: "Publish Unit Tests Results"
        needs: build-and-test
        runs-on: ubuntu-latest
        if: always()
        steps:
            -   name: Download Artifacts
                uses: actions/download-artifact@v2
                with:
                    path: artifacts
            -   name: Publish Unit Test Results
                uses: EnricoMi/publish-unit-test-result-action@v1
                with:
                    files: artifacts/**/*.xml
